#!/bin/bash

# Stash everything temporarily.
# Note that this doesn't create a stash if there are no changes.
NOMIS_TIMESTAMP=$(date "+%Y-%m-%d-%H-%M-%S")
THE_CURRENT_COMMIT_SHA=$(git rev-parse HEAD)
STASH_NAME="_created-by-nomis-cljfmt-v1-pre-push-hook-${NOMIS_TIMESTAMP}-for-${THE_CURRENT_COMMIT_SHA}"
git stash push \
    --quiet \
    --include-untracked \
    --message "${STASH_NAME}"

# Do the checks and let the user know about any failure:
echo -n "Checking formatting..."
lein cljfmt check > /dev/null 2>&1
return_code=$?
if [ $return_code -ne 0 ]
then
    echo "BAD FORMATTING."
    echo "ERROR: cljfmt returned a non-zero exit status -- cannot push."
else
    echo "OK."
fi

# If we created a stash, pop it:
TOP_STASH=$(git stash list | head -1)
if [[ $TOP_STASH =~ ${STASH_NAME} ]]; then
    # Return to original state.
    git stash apply --quiet --index # TODO Change this to pop when are sure all is OK
fi

# Deal with the return value:
if [ $return_code -ne 0 ]
then
    exit 1
fi
