#!/bin/bash

THIS_DIR=$(dirname "${BASH_SOURCE[0]}")

source ${THIS_DIR}/../../../bash/common/git-funs.sh

# Stash everything temporarily, keeping staged files.
# Note that this doesn't create a stash if there are no changes.
THE_CURRENT_COMMIT_SHA=$(git rev-parse HEAD)
STASH_NAME=$(git__return_safekeeping_stash_name "_nomis-cljfmt-for-commit-and-push" "pre-commit" ${THE_CURRENT_COMMIT_SHA})
git stash push \
    --quiet \
    --keep-index \
    --include-untracked \
    --message "${STASH_NAME}"

# Do the checks and let the user know about any failure:
echo -n "Checking formatting..."
lein cljfmt check > /dev/null 2>&1
return_code=$?
if [ $return_code -ne 0 ]
then
    echo "BAD FORMATTING."
    echo "ERROR: cljfmt returned a non-zero exit status -- cannot commit."
else
    echo "OK."
fi

# If we created a stash, pop it:
TOP_STASH=$(git stash list | head -1)
if [[ $TOP_STASH =~ ${STASH_NAME} ]]; then
    # Return to original state.
    # We do a hard reset first to avoid conflicts when a file has both staged
    # and unstaged changes.
    git reset --quiet --hard
    git stash apply --quiet --index # TODO Change this to pop when are sure all is OK
fi

# Deal with the return value:
if [ $return_code -ne 0 ]
then
    exit 1
fi
