#!/bin/bash

touch .git/nomis-100-pre-commit-entered

echo "In post-commit hook"
echo "GIT_DIR =" ${GIT_DIR}

NOMIS_POST_COMMIT_LOCK_FILE=".git/nomis-post-commit-lock-file"

CURRENT_COMMIT_MESSAGE=$(git log --format=%s -n 1)
if [[ $CURRENT_COMMIT_MESSAGE =~ "apply-local-formatting" ]]; then
    touch .git/nomis-200-current-commit-is-apply-local-formatting
    # git reset --quiet --soft HEAD^
    # echo "Done resetting"
else
    touch .git/nomis-300-NOT-current-commit-is-apply-local-formatting
    if [ -f ${NOMIS_POST_COMMIT_LOCK_FILE} ]; then
        touch .git/nomis-400-removing-lock-file
    else
        touch .git/nomis-500-not-removing-lock-file
        touch ${NOMIS_POST_COMMIT_LOCK_FILE}

        #### If previous commit was "apply-local-formatting",
        # TODO Check that commit is not pushed (how do you check that?)
        # TODO Also maybe check that we don't push "apply-local-formatting".

        CURRENT_COMMIT_MESSAGE=$(git log --format=%s -n 1)

        #### Reformat and stage any changes:

        echo "Checking and fixing formatting and committing"

        lein cljfmt fix > /dev/null 2>&1
        WERE_CHANGES_MADE_P=$?

        git add .
        git commit --no-verify --allow-empty -m "apply-cljfmt-formatting"

        echo "Done checking etc"

        # TODO If commit HEAD~2 is apply-local-formatting
        #      then combine the previous three commits
        #           using the second commit's subject and body.

        git reset --soft HEAD~3 &&
            git commit --edit -m"$(git log --format=%B --reverse HEAD..HEAD@{1})"

        # TODO Now we want to set the state back to what it was at the start.

        # git log --format=%s -n 2 | tail -1
        # if that's "apply-local-formatting"
        # - squash last two commits
        # - Do the reset if we can
        # - and apply top stash

        # TOP_STASH=$(git stash list | head -1)
        # if [[ $TOP_STASH =~ "_pre-cljfmt-for-commit" ]]; then
        #     # Return to original state.
        #     # We do a hard reset first to avoid conflicts when a file has both staged
        #     # and unstaged changes.
        #     git reset --quiet --hard
        #     git stash pop --quiet --index
        # fi

        #### Don't recurse infinitely
        #### commit --no-verify --quiet -m "apply-local-formatting"
        rm ${NOMIS_POST_COMMIT_LOCK_FILE}
    fi
fi

touch .git/nomis-999-pre-commit-exited
