#!/bin/bash

echo "In pre-commit hook"
echo "GIT_DIR =" ${GIT_DIR}


#### Stash everything temporarily. Keep staged files.
#### Note that this doesn't create a stash if there are no changes.

#### TODO Take a closer look at these commits. They seem to delete many files.

git stash push \
    --quiet \
    --keep-index \
    --include-untracked \
    --message "_created-by-pre-commit-hook"



if [[ $(git log --format=%s -n 1) == apply-local-formatting* ]]; then
    # TODO Check that commit is not pushed, because in that case what
    #      should we do?
    :
else
    # TODO Apply cljfmt formatting.
    :
fi


echo "Done pre-commit hook"
