#!/bin/bash

if [ -f .git/_nomis-doing-post-commit-rewriting ]; then
    echo 'ERROR in pre-commit hook: .git/_nomis-doing-post-commit-rewriting exists -- something must have gone wrong before -- delete the file so you can continue.'
    exit 1
elif [[ $(git log --format=%s -n 1) == apply-local-formatting* ]]; then
    # TODO Check that commit is not pushed, because in that case what
    #      should we do?
    #      Using this:
    #          THE_BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
    #          git log --pretty=format:%s origin/$THE_BRANCH_NAME..$THE_BRANCH_NAME
    :
fi
