#!/usr/bin/env bash
"exec" "plk" "-Sdeps" "{:paths [\"${HOME}/nomis-git-stuff/src/cljs\"] :deps {com.andrewmcveigh/cljs-time {:mvn/version \"0.5.2\"}}}" "$0" "$@"

(ns nomis-git-stuff.cljfmt-with-local-formatting.hooks.pre-push
  (:require [nomis-git-stuff.cljfmt-with-local-formatting.pre-push :as pre-push]))

(pre-push/pre-push)
