#!/bin/bash

if [ -f .git/_nomis-doing-post-commit-rewriting ]; then
    echo '**** pre-commit hook: We are in nested hooks. You should use --no-verify.'
elif [[ $(git log --format=%s -n 1) == apply-local-formatting* ]]; then
    # TODO Check that commit is not pushed, because in that case what
    #      should we do?
    :
fi
